plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bcp.checkmkagent'
    compileSdk 35

    defaultConfig {
        applicationId 'com.bcp.checkmkagent'
        minSdk 26
        targetSdk 33
        versionCode 2
        versionName '1.1.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
